### ISSUE TITLE
[PENDING] Ru-board: encryption is not enforced

### ISSUE THREAD

**Issue by sergeevabc** [palant/enforceencryption#12] opened 2017-07-07 18:52 UTC
Dear Mr. Palant,
Could you be so kind to investigate this case, please?
1. Open forum.ru-board.com via [https][2] and enforce encryption, then close the tab.
2. Open another yet not enforced site, for example, netall.ru via [https][1] and enforce it, close the tab.
3. Now open the first one via [http][1]. Redirect to https is expected, however it is served via http, why?

[1]: http://forum.ru-board.com/
[2]: https://forum.ru-board.com/
[3]: https://www.netall.ru/

**Comment by sergeevabc** [comment] 2017-07-20 21:00
Err… Hello?

**Comment by palant** [comment] 2017-07-21 11:45
Strange, it seems that Enforce Encryption is broken in Firefox 54 and nobody noticed. The number of parameters to `nsISiteSecurityService.processHeader()` changed but I cannot see immediately when that happened.

Just a side-note: this extension will stop working in Firefox 57, porting it to the Web Extension platform doesn't seem possible.

**Comment by sergeevabc** [comment] 2017-07-21 12:13
Browser is Pale Moon 27.4 x64, its core is based on Firefox 38 ESR according to Wikipedia’s [article][1].

[1]: https://en.wikipedia.org/wiki/Pale_Moon_%28web_browser%29#History

**Comment by jomo** [comment] 2017-07-21 12:31
The change of parameters was introduced by mozilla/gecko-dev@396962011a479a5e26a0511237d0fad4af8eb609 due to [bug 1363546](https://bugzilla.mozilla.org/show_bug.cgi?id=1363546). At least you could now set the `aSource` to `SOURCE_UNKNOWN`

**Comment by palant** [comment] 2017-07-21 17:41
Yes, I saw that change but it landed in Firefox 56. I can see an issue in Firefox 54 however.

**Comment by palant** [comment] 2017-07-21 18:16
Ok, the culprit is [bug 1336867](https://bugzilla.mozilla.org/show_bug.cgi?id=1336867) which removed `unsafeProcessHeader()` in Firefox 54.

**Comment by palant** [comment] 2017-07-21 19:30
I fixed the parameters issue with https://github.com/palant/enforceencryption/commit/6444efa847cb72552d1b1cb6080770c0be6c2cfc. Enforce Encryption 1.0.7 has been released, works fine in Firefox 54 and 56 now. I also tested Ru-board and didn't see any issues. So am going to resolve this bug report, feel free to reopen if you are able to reproduce in a supported Firefox version (Firefox 35 and above). Palemoon is not a supported browser.

**Closed by palant** 2017-07-21 19:30 UTC

**Comment by sergeevabc** [comment] 2017-07-21 19:39
Pale Moon works with XUL and XPCOM addons. Your addon fits into this category. Why no support then?

**Comment by palant** [comment] 2017-07-21 20:59
XUL and XPCOM aren't standardized, each Firefox version introduces changes. It's hard enough to keep up with Firefox changes. An additional browser based on an ancient Firefox version with an assorted mix of changes and bugs applied is not a trivial target to support. If my extensions happen to work there by coincidence or if somebody else does the effort of making them compatible - that's fine with me. Just don't expect me to do this work.

**Comment by sergeevabc** [comment] 2017-07-21 22:32
In case some PM user would look for solution, the workaround is [Moon tester tool][1] + [znHTTPS][2].

[1]: https://addons.palemoon.org/addon/moon-tester-tool/
[2]: https://addons.mozilla.org/en-US/firefox/addon/znhttps/
